# Generated by Django 5.0.7 on 2026-08-24 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['org_id'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.CharField(max_length=50, unique=True)),
                ('location_name', models.CharField(max_length=200)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='reconciliation.organization')),
            ],
            options={
                'ordering': ['location_id'],
            },
        ),
        migrations.CreateModel(
            name='Disagreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(max_length=50)),
                ('reason', models.CharField(choices=[('MISSING_IN_B', 'Missing in B'), ('ORPHAN_IN_B', 'Orphan in B'), ('DUPLICATE_IN_B', 'Duplicate in B'), ('VALUE_MISMATCH', 'Value Mismatch'), ('LOCATION_MISMATCH', 'Location Mismatch')], max_length=50)),
                ('system_a_location', models.CharField(blank=True, max_length=50)),
                ('system_b_location', models.CharField(blank=True, max_length=50)),
                ('system_a_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('system_b_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('system_b_raw_value', models.CharField(blank=True, max_length=200)),
                ('system_b_entry_ids', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True)),
                ('system_a_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disagreements_as_a', to='reconciliation.organization')),
                ('system_b_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disagreements_as_b', to='reconciliation.organization')),
            ],
            options={
                'ordering': ['record_id'],
            },
        ),
        migrations.CreateModel(
            name='SystemARecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(max_length=50, unique=True)),
                ('event_date', models.DateField()),
                ('category_code', models.CharField(max_length=50)),
                ('actor_id', models.CharField(blank=True, max_length=50)),
                ('base_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('adjustment', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('state', models.CharField(max_length=50)),
                ('import_row', models.PositiveIntegerField(help_text='1-based row number in source CSV')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='system_a_records', to='reconciliation.location')),
            ],
            options={
                'ordering': ['record_id'],
            },
        ),
        migrations.CreateModel(
            name='SystemBEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_id', models.CharField(max_length=50, unique=True)),
                ('raw_record_ref', models.CharField(help_text='Exact value from CSV, preserved as-is', max_length=200)),
                ('normalized_record_ref', models.CharField(blank=True, help_text='Normalized form, or null if the reference could not be resolved', max_length=50, null=True)),
                ('recorded_on', models.DateField()),
                ('raw_value', models.CharField(help_text='Exact value from CSV', max_length=200)),
                ('parsed_value', models.DecimalField(blank=True, decimal_places=2, help_text='Parsed Decimal, or null if raw_value was blank or unparseable', max_digits=14, null=True)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('import_row', models.PositiveIntegerField(help_text='1-based row number in source CSV')),
                ('import_notes', models.TextField(blank=True, help_text='Notes about normalization or parse errors')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='system_b_entries', to='reconciliation.location')),
                ('system_a_record', models.ForeignKey(blank=True, help_text='Null if reference is orphaned or unresolvable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='b_entries', to='reconciliation.systemarecord')),
            ],
            options={
                'ordering': ['entry_id'],
            },
        ),
    ]
